spring:
  datasource:
    url: jdbc:mysql://localhost:8889/finalproject?serverTimezone=Asia/Taipei
    username: root
    password: root
  jpa:
  #SessionFactory
    hibernate:
      ddl-auto: validate
    properties:
      hibernat:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  messages:
  #i18n
    basename: error.Messages
    encoding: UTF-8
    fallback-to-system-locale: false
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
server:
  port: 8083
  servlet:
    context-path: /